import os
import math
import time
import json
import requests
from datetime import datetime, timedelta
from flask import Flask, request, jsonify, render_template, session, redirect, url_for
from pymongo import MongoClient
from bson.objectid import ObjectId
import hashlib
import secrets
from dotenv import load_dotenv

load_dotenv(override=True)

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY", secrets.token_hex(32))  # Secret key for sessions

# --- Configuration ---
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/proposeai_db")
app.config["MONGO_URI"] = MONGO_URI

# --- Database Setup ---
try:
    client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=3000)
    client.server_info()
    db = client['proposeai_db']
    users_collection = db['users']
    proposals_collection = db['proposals']
    feedback_collection = db['feedback']
    DB_CONNECTED = True
    print("✅ MongoDB connected successfully.")
except Exception as e:
    DB_CONNECTED = False
    users_collection = None
    proposals_collection = None
    feedback_collection = None
    print(f"⚠️  MongoDB not connected: {e}. Running in demo mode.")

# ============================================================
# PLAN LIMITS
# ============================================================
PLAN_LIMITS = {
    "free":   {"proposals_per_month": 3,     "history": False, "pdf": True,  "send": False, "custom_branding": False},
    "pro":    {"proposals_per_month": 100,   "history": True,  "pdf": True,  "send": True,  "custom_branding": True},
    "agency": {"proposals_per_month": None,  "history": True,  "pdf": True,  "send": True,  "custom_branding": True},
}

PLAN_PRICES = {
    "pro": 1,
    "agency": 2249
}

# UPI ID for payments (Configure in .env or change here)
# User's bank-synced mobile number UPI ID
UPI_ID = os.getenv("UPI_ID", "mppraveen110@okicici") 


PLAN_UPGRADE_MSG = {
    "proposals_per_month": "You've used all {limit} proposals this month on the {plan} plan. Upgrade to the next tier for more!",
    "history":  "Proposal history is a Pro feature. Upgrade to Pro to save and track all your proposals!",
    "pdf":      "PDF export is a Pro feature. Upgrade to Pro to download your proposals as PDFs!",
    "send":     "Sending proposals directly is a Pro feature. Upgrade to Pro to send proposals to clients!",
}


# --- Helpers ---
def hash_password(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()


def get_current_user() -> dict | None:
    if 'user_id' in session:
        if DB_CONNECTED and users_collection is not None:
            try:
                user = users_collection.find_one({"_id": ObjectId(session['user_id'])})
                return user
            except Exception:
                return None
        elif session['user_id'] == 'demo_user':
            return {
                "_id": "demo_user",
                "name": session.get('user_name', "Demo User"),
                "email": "demo@example.com",
                "plan": session.get('demo_plan', 'free'),
                "subscription": {}
            }
    return None


def get_user_plan(user: dict | None) -> str:
    """Return the user's current plan slug, checking for expiry."""
    if user is not None:
        # Check for subscription object
        sub = user.get("subscription", {})
        plan = user.get("plan", "free")
        
        if plan != "free" and sub.get("status") == "active":
            expiry_str = sub.get("expiry_date")
            if expiry_str:
                expiry_dt = datetime.fromisoformat(expiry_str.replace('Z', ''))
                if datetime.utcnow() > expiry_dt:
                    # Plan has expired! Revert in DB
                    if DB_CONNECTED and users_collection is not None:
                        users_collection.update_one(
                            {"_id": user["_id"]},
                            {"$set": {"plan": "free", "subscription.status": "expired"}}
                        )
                    return "free"
            return plan
        return plan
        
    # Check session for demo plan if no DB user
    return session.get("demo_plan", "free")


def get_proposals_this_month(user_id: str) -> int:
    """Count proposals generated by this user in the current calendar month."""
    if not DB_CONNECTED or proposals_collection is None:
        return int(session.get('demo_proposal_count', 0))
    assert proposals_collection is not None  # type narrowing for Pyre2
    now = datetime.utcnow()
    month_start = datetime(now.year, now.month, 1).isoformat() + "Z"
    count: int = proposals_collection.count_documents({
        "user_id": user_id,
        "created_at": {"$gte": month_start}
    })
    return count


from typing import Optional

# --- AI Generation ---
def generate_proposal_with_ai(client_name: str, project_goal: str, timeline: int, price: Optional[float] = None, refinement_note: Optional[str] = None) -> dict:
    """
    Call OpenRouter AI to generate a detailed proposal.
    If price is None, AI will predict it.
    """
    if not OPENROUTER_API_KEY or "***" in OPENROUTER_API_KEY:
        print("⚠️ OPENROUTER_API_KEY is missing or masked. Please provide a full key.")
        return generate_proposal_content(client_name, project_goal, price or 5000, timeline)

    # Using openrouter/free for high availability and zero cost
    model = "openrouter/free" 
    print(f"🚀 Generating proposal using model: {model}")
    
    price_prompt = f"Predicted price: ${price}" if price else "Predict a fair market price for this project."
    refine_prompt = f"Refinement request: {refinement_note}" if refinement_note else ""

    prompt = f"""
    You are a world-class business strategist and proposal writer for a premium agency. 
    Your goal is to transform basic project ideas into persuasive, high-value professional proposals.

    ### Project Context:
    - **Client:** {client_name}
    - **Project Objective:** {project_goal}
    - **Proposed Timeline:** {timeline} weeks
    - **Budget Target:** {price_prompt}
    - **Special Refinement Instructions:** {refinement_note if refinement_note else "None. Create a fresh, comprehensive proposal."}

    ### Instructions for Analysis:
    1. **Executive Summary:** Analyze the project objective and write a compelling summary. Focus on the 'Why' - the business impact, the transformation, and the value proposition. Use professional, modern business language.
    2. **Scope of Work:** Detail exactly WHAT will be done. Break it down into technical requirements, design phases, and business goals. Use bullet points for clarity (in the string).
    3. **Timeline & Milestones:** Create {math.ceil(timeline/2) if timeline > 0 else 2} distinct logical phases. Each phase must have a title, a duration in weeks, a list of at least 3-4 specific deliverables, and a logical price allocation.
    4. **Pricing:** Ensure the total of all milestone prices EQUALS the final total project price. Output prices as numbers (floats).
    5. **Tone:** Premium, authoritative, yet approachable.

    ### output_format (MANDATORY JSON):
    {{
        "id": "PROP-unique-id",
        "createdAt": "ISO-TIMESTAMP",
        "client": {{ 
            "name": "{client_name}", 
            "company": "If the client name implies a company like 'Sarah at Google', put 'Google' here, otherwise use a professional placeholder like '{client_name} Solutions'"
        }},
        "project": {{ 
            "title": "A compelling, high-value project title based on the goal", 
            "goal": "{project_goal}", 
            "timeline": {timeline}, 
            "price": predicted_or_provided_price 
        }},
        "sections": {{
            "executiveSummary": "3-4 paragraphs of deep analysis and strategy...",
            "scopeOfWork": "A detailed multi-paragraph breakdown of activities and standards...",
            "milestones": [
                {{ 
                    "id": 1, 
                    "title": "Discovery & Strategy Architecure", 
                    "duration": "1 week", 
                    "deliverables": ["Technical Audit", "UI/UX Sitemap", "Project Roadmap"], 
                    "price": 1500.00 
                }}
            ],
            "investment": {{ 
                "total": total_price, 
                "breakdown": "Summarize the payment terms (e.g., 25% upfront, etc.)" 
            }},
            "nextSteps": "Professional closing statement and instructions for signing."
        }}
    }}

    Return ONLY the raw JSON object. No preamble or post-script.
    """

    try:
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "HTTP-Referer": "http://localhost:5000", # Optional
                "X-Title": "ProposeAI", # Optional
            },
            data=json.dumps({
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "response_format": { "type": "json_object" }
            }),
            timeout=30
        )
        
        if response.status_code != 200:
            print(f"❌ OpenRouter API Error: {response.status_code} - {response.text}")
            raise Exception(f"AI Service Error: {response.status_code}")

        res_json = response.json()
        if 'choices' not in res_json:
            print(f"❌ Unexpected API Response: {res_json}")
            raise Exception("AI did not return a valid completion.")

        raw_content = res_json['choices'][0]['message']['content']
        print(f"✅ AI Response Received: {raw_content[:100]}...")
        proposal = json.loads(raw_content)
        
        # Ensure ID and timestamps are updated
        proposal["id"] = f"PROP-{int(time.time() * 1000)}"
        proposal["createdAt"] = datetime.utcnow().isoformat() + "Z"
        
        return proposal
    except Exception as e:
        print(f"❌ AI Generation Error: {e}")
        # Return fallback with clear notice in the logs
        return generate_proposal_content(client_name, project_goal, price or 5000, timeline)


# --- Original Mock (Kept for fallback) ---
def generate_proposal_content(client_name: str, project_goal: str, price: float, timeline: int) -> dict:
    # ... (existing mock implementation)
    time.sleep(0.5)
    # Re-using logic but keeping it simple
    price_f = float(price)
    proposal_id = f"PROP-{int(time.time() * 1000)}"
    return {
        "id": proposal_id,
        "createdAt": datetime.utcnow().isoformat() + "Z",
        "client": {"name": client_name, "company": "Company Name"},
        "project": {"title": "Professional Project", "goal": project_goal, "timeline": timeline, "price": price_f},
        "sections": {
            "executiveSummary": f"Proposal for {client_name} regarding {project_goal}.",
            "scopeOfWork": "Discovery, Implementation, and Handover.",
            "milestones": [{"id":1, "title":"Phase 1", "duration":"Full", "deliverables":["Outcome"], "price": price_f}],
            "investment": {"total": price_f, "breakdown": []},
            "nextSteps": "Sign and Pay."
        }
    }


# ============================================================
# ROUTES - Pages
# ============================================================

@app.route('/')
def welcome():
    """Detailed landing/welcome page."""
    return render_template('welcome.html')


@app.route('/dashboard')
def index():
    """Main application dashboard."""
    user = get_current_user()
    if not user and session.get('user_id') != 'demo_user':
        return redirect(url_for('welcome'))
    return render_template('index.html', user=user)


@app.route('/login')
def login_page():
    """Login & Register page."""
    if 'user_id' in session:
        return redirect(url_for('index'))
    return render_template('login.html')


@app.route('/logout')
def logout():
    """Log the user out."""
    session.clear()
    return redirect(url_for('welcome'))


# ============================================================
# API ROUTES - Auth
# ============================================================

@app.route('/api/register', methods=['POST'])
def api_register():
    """Register a new user."""
    try:
        data = request.get_json()
        name: str = (data.get('name') or '').strip()
        email: str = (data.get('email') or '').strip().lower()
        password: str = data.get('password') or ''

        if not name or not email or not password:
            return jsonify({"success": False, "error": "All fields are required."}), 400
        if len(password) < 6:
            return jsonify({"success": False, "error": "Password must be at least 6 characters."}), 400

        if DB_CONNECTED and users_collection is not None:
            existing = users_collection.find_one({"email": email})
            if existing:
                return jsonify({"success": False, "error": "An account with this email already exists."}), 409

            user_doc = {
                "name": name,
                "email": email,
                "password_hash": hash_password(password),
                "created_at": datetime.utcnow().isoformat() + "Z",
                "plan": "free"
            }
            result = users_collection.insert_one(user_doc)
            session['user_id'] = str(result.inserted_id)
            session['user_name'] = name
            return jsonify({"success": True, "redirect": "/dashboard"}), 201
        else:
            # Demo mode — allow without DB
            session['user_id'] = 'demo_user'
            session['user_name'] = name
            return jsonify({"success": True, "redirect": "/dashboard"}), 201

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/login', methods=['POST'])
def api_login():
    """Log in an existing user."""
    try:
        data = request.get_json()
        email: str = (data.get('email') or '').strip().lower()
        password: str = data.get('password') or ''

        if not email or not password:
            return jsonify({"success": False, "error": "Email and password are required."}), 400

        if DB_CONNECTED and users_collection is not None:
            user = users_collection.find_one({"email": email, "password_hash": hash_password(password)})
            if not user:
                return jsonify({"success": False, "error": "Invalid email or password."}), 401
            session['user_id'] = str(user['_id'])
            session['user_name'] = user.get('name', 'User')
            return jsonify({"success": True, "redirect": "/dashboard"}), 200
        else:
            # Demo mode
            session['user_id'] = 'demo_user'
            session['user_name'] = email.split('@')[0].capitalize()
            return jsonify({"success": True, "redirect": "/dashboard"}), 200

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


# ============================================================
# API ROUTES - Proposals
# ============================================================

@app.route('/api/generate-proposal', methods=['POST'])
def generate_proposal():
    """
    Generate a proposal from 4 inputs — enforces plan limits.
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({"success": False, "error": "No data received."}), 400

        client_name: str = str(data.get('clientName') or 'Unknown Client').strip()
        project_goal: str = str(data.get('projectGoal') or 'To be defined').strip()
        price_raw = data.get('projectPrice')
        price: Optional[float] = float(price_raw) if price_raw and str(price_raw).strip() else None
        timeline: int = int(data.get('timeline') or 4)

        if not client_name or not project_goal:
            return jsonify({"success": False, "error": "Client name and project goal are required."}), 400

        # --- PLAN ENFORCEMENT ---
        user = get_current_user()
        plan: str = get_user_plan(user)
        limits: dict = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])
        user_id: str = session.get('user_id', 'anonymous')

        monthly_limit = limits["proposals_per_month"]
        if monthly_limit is not None:
            used: int = get_proposals_this_month(user_id)
            if used >= monthly_limit:
                msg: str = PLAN_UPGRADE_MSG["proposals_per_month"].format(limit=monthly_limit, plan=plan.capitalize())
                return jsonify({
                    "success": False,
                    "error": msg,
                    "upgrade_required": True,
                    "feature": "proposals_per_month"
                }), 403

        # Generate proposal
        proposal: dict = generate_proposal_with_ai(client_name, project_goal, timeline, price)

        # Save to MongoDB if connected
        if DB_CONNECTED and proposals_collection is not None:
            try:
                doc = {
                    "user_id": user_id,
                    "proposal_id": proposal["id"],
                    "client_name": client_name,
                    "raw_input": {
                        "project_goal": project_goal,
                        "project_price": price,
                        "timeline": timeline
                    },
                    "generated_output": proposal,
                    "status": "Draft",
                    "plan_at_creation": plan,
                    "created_at": datetime.utcnow().isoformat() + "Z"
                }
                proposals_collection.insert_one(doc)
            except Exception as db_err:
                print(f"DB save error (non-fatal): {db_err}")
        else:
            # Demo mode: increment session counter
            session['demo_proposal_count'] = int(session.get('demo_proposal_count', 0)) + 1

        return jsonify({
            "success": True,
            "proposal": proposal,
            "plan": plan,
            "used_this_month": get_proposals_this_month(user_id)
        }), 200

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/refine-proposal', methods=['POST'])
def refine_proposal():
    """Refine an existing proposal (increase/decrease budget)."""
    try:
        data = request.get_json()
        current_proposal = data.get('proposal')
        action = data.get('action') # 'increase', 'decrease'
        
        if not current_proposal or not action:
            return jsonify({"success": False, "error": "Missing data."}), 400
            
        client_name = current_proposal['client']['name']
        project_goal = current_proposal['project']['goal']
        timeline = current_proposal['project']['timeline']
        current_price = current_proposal['project']['price']
        
        # Adjust price by 20%
        if action == 'increase':
            new_price = current_price * 1.2
            refinement_note = "Increase the scope and add more advanced features to justify a 20% budget increase."
        else:
            new_price = current_price * 0.8
            refinement_note = "Reduce the scope to fit a 20% budget decrease while keeping core features."
            
        new_proposal = generate_proposal_with_ai(client_name, project_goal, timeline, new_price, refinement_note)
        
        return jsonify({"success": True, "proposal": new_proposal}), 200
        
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500
        

@app.route('/api/proposals')
def get_proposals():
    """Fetch history of proposals for the current user."""
    try:
        user = get_current_user()
        user_id = session.get('user_id', 'anonymous')
        plan = get_user_plan(user)
        
        # Check if history is allowed for this plan
        limits = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])
        if not limits.get("history", False):
            return jsonify({"success": False, "error": "History is a Pro feature.", "upgrade_required": True}), 403

        if DB_CONNECTED and proposals_collection is not None:
            # Fetch last 50 proposals, newest first
            proposals = list(proposals_collection.find(
                {"user_id": user_id},
                {"_id": 0, "proposal_id": 1, "client_name": 1, "created_at": 1, "generated_output.project.title": 1}
            ).sort("created_at", -1).limit(50))
            
            return jsonify({"success": True, "proposals": proposals})
        else:
            return jsonify({"success": True, "proposals": [], "note": "Demo mode: No database records."})

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/proposal/<proposal_id>')
def get_proposal_detail(proposal_id):
    """Fetch full details of a specific proposal."""
    try:
        user_id = session.get('user_id', 'anonymous')
        
        if DB_CONNECTED and proposals_collection is not None:
            doc = proposals_collection.find_one({"proposal_id": proposal_id, "user_id": user_id}, {"_id": 0})
            if not doc:
                return jsonify({"success": False, "error": "Proposal not found."}), 404
            
            return jsonify({"success": True, "proposal": doc["generated_output"]})
        else:
            return jsonify({"success": False, "error": "Database not connected."}), 503

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/proposal/<proposal_id>/rename', methods=['POST'])
def rename_proposal(proposal_id):
    """Rename a specific proposal."""
    try:
        user_id = session.get('user_id', 'anonymous')
        data = request.get_json()
        
        if not data or 'title' not in data:
            print(f"DEBUG ERROR: Missing data in rename request for {proposal_id}")
            return jsonify({"success": False, "error": "New title is required (missing JSON data)."}), 400
            
        new_title = data.get('title', '').strip()
        
        if not new_title:
            return jsonify({"success": False, "error": "New title cannot be empty."}), 400

        if DB_CONNECTED and proposals_collection is not None:
            # We update the title inside the generated_output object
            print(f"DEBUG: Renaming proposal {proposal_id} for user {user_id} to '{new_title}'")
            result = proposals_collection.update_one(
                {"proposal_id": proposal_id, "user_id": user_id},
                {"$set": {"generated_output.project.title": new_title}}
            )
            print(f"DEBUG: Update result - Matched: {result.matched_count}, Modified: {result.modified_count}")
            
            if result.matched_count == 0:
                # Let's check if the proposal exists at all with ANY user_id for debugging
                exists = proposals_collection.find_one({"proposal_id": proposal_id})
                if exists:
                    print(f"DEBUG WARNING: Proposal {proposal_id} exists but is owned by {exists.get('user_id')}, not {user_id}")
                else:
                    print(f"DEBUG WARNING: Proposal {proposal_id} not found at all in DB.")
                return jsonify({"success": False, "error": "Proposal not found or access denied."}), 404
                
            return jsonify({"success": True, "message": "Proposal renamed successfully!"})
        else:
            return jsonify({"success": False, "error": "Database not connected."}), 503

    except Exception as e:
        print(f"DEBUG CRITICAL ERROR in rename: {str(e)}")
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/proposal/<proposal_id>', methods=['DELETE'])
def delete_proposal(proposal_id):
    """Delete a specific proposal."""
    try:
        user_id = session.get('user_id', 'anonymous')
        
        if DB_CONNECTED and proposals_collection is not None:
            print(f"DEBUG: Deleting proposal {proposal_id} for user {user_id}")
            result = proposals_collection.delete_one({"proposal_id": proposal_id, "user_id": user_id})
            print(f"DEBUG: Delete result - Deleted: {result.deleted_count}")
            
            if result.deleted_count == 0:
                # Debug check
                exists = proposals_collection.find_one({"proposal_id": proposal_id})
                if exists:
                    print(f"DEBUG WARNING: Delete failed. Proposal {proposal_id} owned by {exists.get('user_id')}, current session is {user_id}")
                return jsonify({"success": False, "error": "Proposal not found or access denied."}), 404
                
            return jsonify({"success": True, "message": "Proposal deleted successfully!"})
        else:
            return jsonify({"success": False, "error": "Database not connected."}), 503

    except Exception as e:
        print(f"DEBUG CRITICAL ERROR in delete: {str(e)}")
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/feedback', methods=['POST'])
def save_feedback():
    """Save user feedback and mark them as having given feedback."""
    try:
        user_id = session.get('user_id', 'anonymous')
        data = request.get_json()
        if not data:
            return jsonify({"success": False, "error": "No data received."}), 400

        features = data.get('features', '').strip()
        bugs = data.get('bugs', '').strip()
        rating = data.get('rating', 5)

        if DB_CONNECTED and feedback_collection is not None:
            # Save feedback
            feedback_doc = {
                "user_id": user_id,
                "user_name": session.get('user_name', 'Anonymous'),
                "features": features,
                "bugs": bugs,
                "rating": rating,
                "created_at": datetime.utcnow().isoformat() + "Z"
            }
            feedback_collection.insert_one(feedback_doc)

            # Mark user as having given feedback
            if user_id != 'demo_user' and users_collection is not None:
                users_collection.update_one(
                    {"_id": ObjectId(user_id)},
                    {"$set": {"feedback_given": True}}
                )
            else:
                session['feedback_given'] = True

            return jsonify({"success": True, "message": "Thank you for your feedback! ✨"})
        else:
            # Demo mode
            session['feedback_given'] = True
            return jsonify({"success": True, "message": "Demo mode: Feedback received (not saved to DB)."})

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/feedbacks')
def get_feedbacks():
    """Return all feedbacks to display above the footer."""
    try:
        if DB_CONNECTED and feedback_collection is not None:
            # Get latest 12 feedbacks (fits grid better)
            feedbacks = list(feedback_collection.find().sort("created_at", -1).limit(12))
            # Convert ObjectId to string for JSON serialization
            for f in feedbacks:
                f['_id'] = str(f['_id'])
            return jsonify({"success": True, "feedbacks": feedbacks})
        else:
            # Return empty if DB not connected, to avoid "fake data"
            return jsonify({"success": True, "feedbacks": []})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/user-status')
def user_status():
    """Return the current user's plan and usage info."""
    user = get_current_user()
    plan: str = get_user_plan(user)
    limits: dict = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])
    user_id: str = session.get('user_id', 'anonymous')
    used: int = get_proposals_this_month(user_id)
    monthly_limit = limits["proposals_per_month"]
    
    subscription = {}
    if user:
        subscription = user.get("subscription", {
            "status": "none",
            "expiry_date": None
        })

    # Total proposals ever
    total_proposals = 0
    feedback_given = session.get('feedback_given', False)
    if DB_CONNECTED and proposals_collection is not None:
        total_proposals = proposals_collection.count_documents({"user_id": user_id})
        if user:
            feedback_given = user.get("feedback_given", False)

    return jsonify({
        "logged_in": user is not None or user_id == 'demo_user',
        "plan": plan,
        "limits": limits,
        "used_this_month": used,
        "total_proposals": total_proposals,
        "feedback_given": feedback_given,
        "remaining": max(0, monthly_limit - used) if monthly_limit is not None else None,
        "limit": monthly_limit,
        "subscription": subscription
    })


@app.route('/api/check-feature', methods=['POST'])
def check_feature():
    """Check if the current user's plan includes a given feature."""
    data = request.get_json() or {}
    feature: str = str(data.get('feature', ''))
    user = get_current_user()
    plan: str = get_user_plan(user)
    limits: dict = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])

    if feature not in limits:
        return jsonify({"allowed": True})

    allowed: bool = bool(limits.get(feature, False))
    if not allowed:
        msg: str = PLAN_UPGRADE_MSG.get(feature, f"This feature requires a higher plan. Upgrade to Pro!")
        return jsonify({"allowed": False, "error": msg, "upgrade_required": True})

    return jsonify({"allowed": True})


# --- Actual Delivery Helpers ---
def generate_pdf(proposal: dict) -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        print("fpdf2 not installed efficiently.")
        return b""
    
    class PDF(FPDF):
        def header(self):
            # Brand Teal Header
            self.set_fill_color(0, 212, 170)
            self.rect(0, 0, 210, 40, 'F')
            self.set_font("Helvetica", style="B", size=32)
            self.set_text_color(255, 255, 255)
            self.cell(0, 30, txt="PROPOSE AI", ln=True, align='C')
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", size=8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f"Page {self.page_no()}", align='C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.ln(15) # Space after header
    
    # Project Title
    pdf.set_font("Helvetica", style="B", size=22)
    pdf.set_text_color(40, 40, 40)
    title = proposal.get('project', {}).get('title', 'Project Proposal')
    pdf.multi_cell(0, 12, txt=str(title), align='C')
    
    pdf.set_font("Helvetica", size=12)
    pdf.set_text_color(100, 100, 100)
    client_name = proposal.get('client', {}).get('name', 'Client')
    pdf.cell(0, 10, txt=f"Prepared for: {client_name}", ln=True, align='C')
    pdf.ln(10)
    
    # ---------------------------------------------------------
    # Content Sections
    # ---------------------------------------------------------
    sections = proposal.get('sections', {})
    
    # Priority sections to render first if they exist
    priority_keys = ['executiveSummary', 'scopeOfWork', 'objectives']
    
    for k in priority_keys:
        if k in sections and sections[k]:
            v = sections[k]
            pdf.set_font("Helvetica", style="B", size=14)
            pdf.set_text_color(0, 160, 130) # Dark teal
            section_title = str(k).replace('_', ' ').replace('Summary', ' Summary').title()
            pdf.cell(0, 10, txt=section_title, ln=True)
            pdf.set_draw_color(0, 212, 170)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 40, pdf.get_y())
            pdf.ln(3)
            
            pdf.set_font("Helvetica", size=11)
            pdf.set_text_color(60, 60, 60)
            safe_txt = str(v).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 7, txt=safe_txt)
            pdf.ln(8)

    # Any other sections
    for k, v in sections.items():
        if k not in priority_keys and k not in ['milestones', 'investment', 'nextSteps'] and v:
            pdf.set_font("Helvetica", style="B", size=14)
            pdf.set_text_color(0, 160, 130)
            pdf.cell(0, 10, txt=str(k).replace('_', ' ').title(), ln=True)
            pdf.ln(2)
            pdf.set_font("Helvetica", size=11)
            pdf.set_text_color(60, 60, 60)
            safe_txt = str(v).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 7, txt=safe_txt)
            pdf.ln(8)

    # ---------------------------------------------------------
    # Milestones & Investment Table
    # ---------------------------------------------------------
    milestones = sections.get('milestones', [])
    if not milestones:
        # Check top level
        milestones = proposal.get('milestones', [])

    if milestones:
        pdf.add_page() # New page for timeline
        pdf.ln(10)
        pdf.set_font("Helvetica", style="B", size=16)
        pdf.set_text_color(0, 160, 130)
        pdf.cell(0, 12, txt="Project Timeline & Investment", ln=True)
        pdf.ln(5)
        
        # Table Header
        pdf.set_font("Helvetica", style="B", size=11)
        pdf.set_fill_color(245, 245, 245)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(100, 10, "Milestone / Deliverable", border=1, fill=True)
        pdf.cell(40, 10, "Timeline", border=1, fill=True)
        pdf.cell(40, 10, "Investment", border=1, fill=True, ln=True)
        
        pdf.set_font("Helvetica", size=10)
        for m in milestones:
            title = m.get('title') or m.get('name', 'Phase')
            duration = m.get('duration', 'TBD')
            price = m.get('price', 0)
            
            # Use multi_cell for title to wrap
            curr_y = pdf.get_y()
            pdf.multi_cell(100, 10, txt=str(title), border=1)
            next_y = pdf.get_y()
            
            pdf.set_xy(110, curr_y)
            pdf.cell(40, next_y - curr_y, txt=str(duration), border=1)
            pdf.cell(40, next_y - curr_y, txt=f"${price:,}", border=1, ln=True)

    # Investment Breakdown
    investment = sections.get('investment', {})
    if investment and investment.get('breakdown'):
        pdf.ln(10)
        pdf.set_font("Helvetica", style="B", size=12)
        pdf.cell(0, 8, "Payment Terms", ln=True)
        pdf.set_font("Helvetica", size=10)
        pdf.multi_cell(0, 6, txt=str(investment['breakdown']))

    # Next Steps
    next_steps = sections.get('nextSteps')
    if next_steps:
        pdf.ln(10)
        pdf.set_font("Helvetica", style="I", size=11)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 7, txt=str(next_steps))
            
    # Final Total
    pdf.ln(15)
    pdf.set_fill_color(0, 212, 170)
    pdf.rect(130, pdf.get_y(), 70, 15, 'F')
    pdf.set_xy(130, pdf.get_y())
    pdf.set_font("Helvetica", style="B", size=16)
    pdf.set_text_color(255, 255, 255)
    total_price = proposal.get('project', {}).get('price', 0)
    pdf.cell(70, 15, txt=f"TOTAL: ${total_price:,}", ln=True, align='C')
    
    return bytes(pdf.output())

def send_email_with_pdf(recipient: str, proposal: dict, pdf_bytes: bytes):
    SMTP_EMAIL = os.getenv("SMTP_EMAIL")
    SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
    if not SMTP_EMAIL or not SMTP_PASSWORD or SMTP_EMAIL == "your_email@gmail.com":
        raise Exception("SMTP credentials not configured in .env. Please add them.")
        
    import smtplib
    from email.message import EmailMessage
    
    title = proposal.get('project', {}).get('title', 'Project Proposal')
    
    msg = EmailMessage()
    msg['Subject'] = f"Proposal: {title}"
    msg['From'] = SMTP_EMAIL
    msg['To'] = recipient
    msg.set_content(f"Hello,\n\nPlease find attached the proposal for {title}.\n\nBest regards,\nProposeAI")
    
    try:
        if pdf_bytes:
            msg.add_attachment(pdf_bytes, maintype='application', subtype='pdf', filename='proposal.pdf')
            
        if not SMTP_EMAIL or not SMTP_PASSWORD:
            print("❌ SMTP_EMAIL or SMTP_PASSWORD not set in environment.")
            raise Exception("SMTP credentials missing.")

        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(str(SMTP_EMAIL), str(SMTP_PASSWORD))
            server.send_message(msg)
            print(f"✅ Email sent successfully to {recipient}")
    except Exception as e:
        err_str = str(e)
        if "535" in err_str or "Username and Password not accepted" in err_str:
             print("❌ Gmail Authentication Failed: Invalid credentials or App Password missing.")
             raise Exception("Gmail Authentication Failed. Please use a 16-character 'App Password' from your Google Account settings.")
        print(f"❌ SMTP Error while sending to {recipient}: {err_str}")
        raise e


@app.route('/api/contact', methods=['POST'])
def api_contact():
    """Handle contact form submissions by sending an email to the admin."""
    try:
        data = request.get_json() or {}
        name = data.get('name', '').strip()
        email = data.get('email', '').strip()
        subject = data.get('subject', '').strip()
        message = data.get('message', '').strip()

        if not name or not email or not message:
            return jsonify({"success": False, "error": "Name, Email and Message are required."}), 400

        # SMTP details
        admin_email = os.getenv("SMTP_EMAIL", "mppraveen110@gmail.com")
        smtp_pass = os.getenv("SMTP_PASSWORD")

        if not smtp_pass:
             print(f"⚠️ SMTP password not found in .env. Message from {name} ({email}) discarded.")
             return jsonify({"success": False, "error": "Email delivery is currently disabled. Admin has not set up SMTP credentials."}), 503

        # Send email to admin
        import smtplib
        from email.message import EmailMessage

        msg = EmailMessage()
        msg['Subject'] = f"Contact Form: {subject or 'General Inquiry'}"
        msg['From'] = admin_email
        msg['To'] = admin_email
        msg['Reply-To'] = email
        msg.set_content(f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}")

        if not admin_email or not smtp_pass:
            print("❌ Admin email or SMTP password not set for contact form.")
            return jsonify({"success": False, "error": "Contact form is misconfigured."}), 500

        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(str(admin_email), str(smtp_pass))
            server.send_message(msg)
            print(f"✅ Contact message from {name} sent to admin.")

        # Save to database for record-keeping
        if DB_CONNECTED:
            try:
                db['contacts'].insert_one({
                    "name": name,
                    "email": email,
                    "subject": subject,
                    "message": message,
                    "created_at": datetime.utcnow().isoformat() + "Z"
                })
                print(f"✅ Contact message from {name} saved to DB.")
            except Exception as db_err:
                print(f"⚠️ Failed to save contact to DB: {db_err}")

        return jsonify({"success": True, "message": "Your message has been sent to our team! ✨"})
    except Exception as e:
        err_str = str(e)
        if "535" in err_str or "Username and Password not accepted" in err_str:
             return jsonify({"success": False, "error": "Gmail Authentication Failed: You MUST use a 16-character 'App Password' from your Google Account settings, not your regular password."}), 401
        print(f"❌ Contact Email Error: {e}")
        return jsonify({"success": False, "error": f"Failed to send message: {err_str}"}), 500

@app.route('/api/send-proposal', methods=['POST'])
def send_proposal():
    """Actually send a proposal to a client via email."""
    import re
    try:
        data = request.get_json() or {}
        proposal_id = data.get('proposal_id')
        recipient = data.get('recipient', '').strip()
        password = data.get('password', '')
        user_id = session.get('user_id', 'anonymous')
        
        if not proposal_id:
            return jsonify({"success": False, "error": "Proposal ID required."}), 400
            
        if not recipient or not password:
            return jsonify({"success": False, "error": "Recipient and Password are required."}), 400

        # Validate password
        if user_id != 'demo_user' and DB_CONNECTED and users_collection is not None:
            user = users_collection.find_one({
                "_id": ObjectId(user_id),
                "password_hash": hash_password(password)
            })
            if not user:
                return jsonify({"success": False, "error": "Invalid password. Unauthorized."}), 401
        elif user_id == 'demo_user' and password != 'demo':
            pass

        if '@' not in recipient:
            return jsonify({"success": False, "error": "Invalid format. Please provide a valid email address."}), 400

        # Fetch proposal details
        proposal_data = {"project": {"title": "Demo Proposal", "price": 0}}
        if DB_CONNECTED and proposals_collection is not None:
            doc = proposals_collection.find_one({"proposal_id": proposal_id, "user_id": user_id})
            if doc and "generated_output" in doc:
                proposal_data = doc["generated_output"]
        
        msg = "Sent successfully."
        try:
            pdf_bytes = generate_pdf(proposal_data)
            send_email_with_pdf(recipient, proposal_data, pdf_bytes)
            msg = f"Proposal securely sent with PDF via Email to {recipient}"
        except Exception as delivery_err:
            return jsonify({"success": False, "error": f"Delivery failed: {str(delivery_err)}"}), 500

        # Update status in DB
        if DB_CONNECTED and proposals_collection is not None:
            proposals_collection.update_one(
                {"proposal_id": proposal_id, "user_id": user_id},
                {"$set": {"status": "sent", "sent_at": datetime.now()}}
            )
            
        return jsonify({
            "success": True, 
            "message": msg,
            "status": "sent"
        })

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/webhook/payment', methods=['POST'])
def payment_webhook():
    """Handle successful payment notifications (webhook)."""
    try:
        data = request.get_json() or {}
        # In a real app, verify signature here (e.g., Stripe-Signature)
        
        email = data.get('email')
        plan = data.get('plan') # 'pro' or 'agent'
        payment_id = data.get('payment_id')
        
        if not email or not plan:
            return jsonify({"success": False, "error": "Invalid webhook data"}), 400
            
        if DB_CONNECTED and users_collection is not None:
            now = datetime.utcnow()
            expiry = now + timedelta(days=30)
            
            users_collection.update_one(
                {"email": email},
                {
                    "$set": {
                        "plan": plan,
                        "subscription": {
                            "status": "active",
                            "start_date": now.isoformat() + "Z",
                            "expiry_date": expiry.isoformat() + "Z",
                            "payment_id": payment_id,
                            "last_updated": now.isoformat() + "Z"
                        }
                    }
                },
                upsert=True
            )
            print(f"DEBUG: Subscription activated for {email} (Plan: {plan})")
            return jsonify({"success": True, "message": "Subscription activated!"})
        else:
            return jsonify({"success": False, "error": "Database not connected"}), 503
            
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/payment')
def payment_page():
    """Render the premium payment page."""
    user = get_current_user()
    if not user:
        return redirect(url_for('login_page'))
        
    plan_slug = request.args.get('plan', 'pro').lower()
    if plan_slug not in PLAN_PRICES:
        return redirect(url_for('index'))
        
    price = PLAN_PRICES[plan_slug]
    plan_name = plan_slug.capitalize()
    
    # UPI URI: upi://pay?pa=address&pn=name&am=amount&cu=currency
    # Added transaction note (tn) for better identification
    upi_uri = f"upi://pay?pa={UPI_ID}&pn=ProposeAI&am={price}&cu=INR&tn=ProposeAI%20{plan_name}%20Upgrade"

    
    # Get plan features for display
    features = []
    if plan_slug == 'pro':
        features = ["100 proposals/month", "Save History", "PDF Downloads", "Send to Client", "Custom Branding"]
    elif plan_slug == 'agency':
        features = ["Unlimited Proposals", "Everything in Pro", "5 Team Members", "Priority Support", "White-label Reports"]

    return render_template('payment.html', 
                         plan=plan_slug, 
                         plan_name=plan_name, 
                         price=price, 
                         upi_id=UPI_ID,
                         upi_uri=upi_uri,
                         features=features)


@app.route('/api/request-payment-otp', methods=['POST'])
def request_payment_otp():
    """Generates a secure 6-digit OTP, stores it in session, and emails the user."""
    user = get_current_user()
    if not user:
        return jsonify({"success": False, "error": "Login required"}), 401
    
    data = request.get_json() or {}
    plan = data.get('plan', '').lower()
    
    if not plan:
        return jsonify({"success": False, "error": "Invalid plan data"}), 400
        
    otp = str(secrets.randbelow(899999) + 100000) # 100000 to 999999
    expiry = datetime.utcnow().timestamp() + 60 # Strictly 60 seconds
    
    is_demo = not (DB_CONNECTED and users_collection is not None)
    user_email = user.get("email", "").strip()
    
    # If in demo mode, fallback to hardcoded OTP without sending real emails
    if is_demo or not user_email:
        session['payment_otp'] = {"otp": "123456", "expires_at": expiry + 3600}
        return jsonify({"success": True, "message": "Demo Mode: Check alert for OTP!"})

    session['payment_otp'] = {"otp": otp, "expires_at": expiry}
    
    try:
        admin_email = os.getenv("SMTP_EMAIL", "").strip()
        smtp_pass = os.getenv("SMTP_PASSWORD", "").strip()
        if admin_email and smtp_pass:
            import smtplib
            from email.message import EmailMessage
            
            msg = EmailMessage()
            msg['Subject'] = f"ProposeAI - Verification OTP ({plan.upper()})"
            msg['From'] = admin_email
            msg['To'] = user_email
            
            content = (
                f"Hello {user.get('name', 'User')},\n\n"
                f"Your 6-digit Activation Code for the {plan.upper()} plan upgrade is:\n\n"
                f"{otp}\n\n"
                f"This acts as a secure One-Time Password. It will expire in 60 seconds and cannot be reused after activation.\n\n"
                f"ProposeAI Team"
            )
            msg.set_content(content)
            
            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(admin_email, smtp_pass)
                server.send_message(msg)
                
        return jsonify({"success": True, "message": "OTP sent to your email!"})
    except Exception as e:
        # Prevent lockouts if SMTP crashes by failing loudly back to the UI
        session.pop('payment_otp', None)
        return jsonify({"success": False, "error": f"Failed to send OTP email: {str(e)}"}), 500


@app.route('/api/submit-payment', methods=['POST'])
def submit_payment():
    """Handle UTR (Transaction ID) and OTP Validation."""
    user = get_current_user()
    if not user:
        return jsonify({"success": False, "error": "Login required"}), 401
        
    data = request.get_json() or {}
    plan = data.get('plan', '').lower()
    otp_entered = data.get('otp', '').strip()
    
    if not plan or plan not in PLAN_PRICES:
        return jsonify({"success": False, "error": "Invalid payment data"}), 400
        
    # --- OTP Validation Logic ---
    stored = session.get('payment_otp')
    if not stored:
        return jsonify({"success": False, "error": "OTP was not requested or has expired. Please request a new one."}), 400
        
    if datetime.utcnow().timestamp() > stored.get("expires_at", 0):
        session.pop('payment_otp', None)
        return jsonify({"success": False, "error": "OTP has expired after 60 seconds. Please request a new one."}), 400
        
    if stored.get("otp") != otp_entered:
        return jsonify({"success": False, "error": "Invalid OTP entered. Please try again."}), 400
        
    # OTP is valid! We can securely wipe the token and proceed.
    session.pop('payment_otp', None)
        
    # Default success response messages
    response_msg = f"Payment submitted! Plan {plan.upper()} activated successfully. 🎉"
    is_demo = False

    # 1. Update DB or Session
    if DB_CONNECTED and users_collection is not None:
        try:
            now = datetime.utcnow()
            expiry = now + timedelta(days=30)
            
            users_collection.update_one(
                {"_id": user["_id"]},
                {
                    "$set": {
                        "plan": plan,
                        "subscription": {
                            "status": "active",
                            "start_date": now.isoformat() + "Z",
                            "expiry_date": expiry.isoformat() + "Z",
                            "utr": utr,
                            "last_updated": now.isoformat() + "Z"
                        }
                    }
                }
            )
        except Exception as e:
            return jsonify({"success": False, "error": str(e)}), 500
    else:
        # Fallback for demo mode
        session['demo_plan'] = plan
        response_msg = "Demo Payment Success! (Non-DB mode)"
        is_demo = True

    # 2. Extract user details safely for email
    user_email = user.get("email", "").strip() if user else ""
    user_name = user.get("name", "User") if user else "Demo User"
    
    # Send Payment Receipt to User & Admin
    mail_status = {"user": "skipped", "admin": "skipped"}
    try:
        admin_email = os.getenv("SMTP_EMAIL", "mppraveen110@gmail.com").strip()
        smtp_pass = os.getenv("SMTP_PASSWORD", "").strip()
        
        if not smtp_pass:
            mail_status["error"] = "No SMTP_PASSWORD found in environment"
        elif admin_email and smtp_pass:
            import smtplib
            from email.message import EmailMessage
            
            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(admin_email, smtp_pass)
                
                # Email 1: To the User
                if user_email and "@" in user_email:
                    try:
                        msg_user = EmailMessage()
                        msg_user['Subject'] = f"ProposeAI - Payment Received ({plan.upper()} Plan)"
                        msg_user['From'] = admin_email
                        msg_user['To'] = user_email
                        
                        demo_flag = "[DEMO MODE] " if is_demo else ""
                        content_user = (
                            f"Hello {user_name},\n\n"
                            f"We have received your payment submission for the {plan.upper()} plan.\n\n"
                            f"UPI Ref No: {utr}\n\n"
                            f"Your {demo_flag}plan has been activated successfully! You can jump right in and start generating premium proposals immediately.\n\n"
                            f"(If we find any discrepancy verifying your UTR, our support team will reach out).\n\n"
                            f"Thank you for upgrading,\nProposeAI Team"
                        )
                        msg_user.set_content(content_user)
                        server.send_message(msg_user)
                        mail_status["user"] = "sent"
                    except Exception as eu:
                        mail_status["user"] = f"failed: {eu}"
                else:
                    mail_status["user"] = f"skipped (invalid email: {user_email})"
                        
                # Email 2: To the Admin (You)
                try:
                    msg_admin = EmailMessage()
                    msg_admin['Subject'] = f"🚀 NEW UPGRADE: {user_name} ({plan.upper()})"
                    msg_admin['From'] = admin_email
                    msg_admin['To'] = admin_email
                    
                    content_admin = (
                        f"A user just submitted a payment!\n\n"
                        f"User Name: {user_name}\n"
                        f"User Email: {user_email}\n"
                        f"Plan Selected: {plan.upper()}\n"
                        f"Submitted UPI Ref No: {utr}\n\n"
                        f"Action Required: Please check your PhonePe/GPay to verify this UTR. The user's account has been provisionally activated."
                    )
                    msg_admin.set_content(content_admin)
                    server.send_message(msg_admin)
                    mail_status["admin"] = "sent"
                except Exception as ea:
                    mail_status["admin"] = f"failed: {ea}"
                    
    except Exception as mail_err:
        mail_status["error"] = f"Critical Mail Error: {mail_err}"
        
    return jsonify({
        "success": True, 
        "message": f"{response_msg}\n\nMAIL LOG:\n{mail_status}",
        "mail_debug": mail_status
    })


@app.route('/api/upgrade-plan', methods=['POST'])
def upgrade_plan():
    """Redirects to payment (Legacy endpoint kept for compatibility if needed)."""
    return jsonify({"success": True, "redirect": "/payment"})



if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
